### ISSUE TITLE
Import problem in training stage

### ISSUE THREAD

**Issue by lajictw** [cvignac/DiGress#73]
Hi! I met an import problem in training stage. When running the main.py, it reports 

> Error executing job with overrides: []
> Traceback (most recent call last):
>   File "/mnt/c/Users/14242/Desktop/PaperCode/DiGress/./src/main.py", line 104, in main
>     from metrics.molecular_metrics import TrainMolecularMetrics, SamplingMolecularMetrics
>   File "/mnt/c/Users/14242/Desktop/PaperCode/DiGress/src/metrics/molecular_metrics.py", line 1, in <module>
>     from rdkit import Chem
>   File "/home/ctw/anaconda3/envs/GNN/lib/python3.9/site-packages/rdkit/Chem/__init__.py", line 16, in <module>
>     from rdkit.Chem import rdchem
> TypeError: No registered converter was able to produce a C++ rvalue of type std::string from this Python object of type str

But if I run the

>  from metrics.molecular_metrics import TrainMolecularMetrics, SamplingMolecularMetrics

 alone, I don't have this problem. Screenshots of the run have been attached below. Thanks for your help!
![image](https://github.com/cvignac/DiGress/assets/40271784/beee07b2-4708-45b8-934f-44bb499a863b)
Rdkit is also available. 
![image](https://github.com/cvignac/DiGress/assets/40271784/595d28f9-b57a-4a28-8ce8-ece3826a31e6)

**Comment by cvignac** [comment]
Hello, did you run `pip install -e .` in the root folder? 

You can try to import rdkit at the first line of main.py, sometimes it works. Apart from that, I am not able to help you unfortunately.

**Comment by HeartrooT** [comment]
I had met and solved it, move the error import sentence to the first line of the main.py

**Comment by lajictw** [comment]
> I had met and solved it, move the error import sentence to the first line of the main.py

Thanks! I will check it out!
