### ISSUE TITLE
meet error while running

### ISSUE THREAD

**Issue by Icamd** [cvignac/DiGress#76]
Thank you for your beautiful code! I meet an error when running the command: python3 main.py. The terminal said: 

Found rdkit, all good
<frozen importlib._bootstrap>:228: RuntimeWarning: to-Python converter for std::pair<double, double> already registered; second conversion method ignored.
Processing...
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/proj/DiGress/src/main.py", line 110, in main
    datamodule = qm9_dataset.QM9DataModule(cfg)
  File "/home/proj/DiGress/src/datasets/qm9_dataset.py", line 212, in __init__
    datasets = {'train': QM9Dataset(stage='train', root=root_path, remove_h=cfg.dataset.remove_h,
  File "/home/proj/DiGress/src/datasets/qm9_dataset.py", line 70, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/torch_geometric/data/in_memory_dataset.py", line 57, in __init__
    super().__init__(root, transform, pre_transform, pre_filter, log)
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 97, in __init__
    self._process()
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 230, in _process
    self.process()
  File "/home/proj/DiGress/src/datasets/qm9_dataset.py", line 136, in process
    target_df = pd.read_csv(self.split_paths[self.file_idx], index_col=0)
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 933, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1217, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/home/anaconda3/envs/digress/lib/python3.9/site-packages/pandas/io/common.py", line 789, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/proj/DiGress/data/qm9/qm9_pyg/raw/train.csv'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

Do you know how to solve the problem? Thank you very much!

**Comment by Zhaozhenyu1228** [comment]
May I ask if you have resolved this issue? Thank you for your response.
